DjangoGdsc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('items/',include('item.urls')),
    path('admin/',admin.site.urls),
    path('myitems/',include('myitems.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth import views as authViews
from . import views
from .forms import LoginForm

app_name='core'

urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name="contact"),
    path('search/',views.item_search, name='item_search'),
    path('signup/',views.Signup,name="signup"),
    path('logout/',views.logout, name='logout'),
    path('login/',authViews.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),name='login')
 
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/',views.new,name="new"),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete',views.delete,name='delete'),
     path('<int:pk>/edit/',views.edit,name='edit')
    
]

myitems/urls.py
from django.urls import path

from . import views

app_name="myitems"

urlpatterns = [
    path('',views.index,name="index")
]

item/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class PriorityTag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    priority_tag = models.ForeignKey(PriorityTag, related_name='items', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

myitems/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
      username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-3 px-6 text-slate-700 rounded-xl'
    }))
      password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-3 px-6 rounded-xl text-slate-700'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','email','password1','password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-3 px-6 rounded-xl text-slate-700'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-3 px-6 rounded-xl text-slate-700'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-3 px-6 rounded-xl text-slate-700'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat Password',
        'class': 'w-full py-3 px-6 rounded-xl text-slate-700'
    }))

item/forms.py
from django import forms 
from .models import Item

FORM_CLASS = 'w-full m-2 px-4 py-2 rounded-xl border text-slate-700'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields=('category','priority_tag','name','description','price','image')
        widgets={
            'category': forms.Select(attrs={
                'class':FORM_CLASS
            }),
            'priority_tag': forms.Select(attrs={
                'class':FORM_CLASS
            }),
            'name': forms.TextInput(attrs={
                'class':FORM_CLASS
            }),
            'description': forms.Textarea(attrs={
                'class':FORM_CLASS,'rows':6,'cols':20,'style': 'resize: none;'
            }),
            'price': forms.TextInput(attrs={
                'class':FORM_CLASS
            }),
            'image': forms.FileInput(attrs={
                'class':'w-full m-2 px-4 py-2 rounded-xl border bg-slate-200 text-slate-700'
            })
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields=('category','priority_tag','name','description','price','image')
        widgets={
            'category': forms.Select(attrs={
                'class':FORM_CLASS
            }),
            'priority_tag': forms.Select(attrs={
                'class':FORM_CLASS
            }),
            'name': forms.TextInput(attrs={
                'class':FORM_CLASS
            }),
            'description': forms.Textarea(attrs={
                'class':FORM_CLASS,'rows':6,'cols':20,'style': 'resize: none;'
            }),
            'price': forms.TextInput(attrs={
                'class':FORM_CLASS
            }),
            'image': forms.FileInput(attrs={
                'class':'w-full m-2 px-4 py-2 rounded-xl border bg-slate-200 text-slate-700'
            })
        }
    

core/views.py
from django.shortcuts import render, redirect

from item.models import Category,Item
from django.contrib.auth import logout as logouts 

from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.all()
    categories = Category.objects.all()
    return render(request, 'core/index.html',{
        'items': items,
        'categories': categories
    })

def contact(request):
    return render(request, 'core/contact.html')

def item_search(request):
    query=request.GET.get('q')
    items=Item.objects.filter(name__icontains=query)
    context={'items':items,'query':query}
    return render(request,'core/search_result.html',context)

def Signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form=SignupForm()
    return render(request, 'core/signup.html',{
        'form':form
    })

def logout(request):
    if request.method == 'POST':
        logouts(request)
        return redirect("/")

item/views.py
from django.shortcuts import get_object_or_404, render,redirect
from .models import Item
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm

# Create your views here.

def detail(request,pk):
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(category=item.category).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html',{
        'item': item,
        'related_items': related_items
    })

@login_required
def new(request):
    if request.method == "POST":
        form=NewItemForm(request.POST,request.FILES)
        if form.is_valid:
            # not saving directly becoz created by field missing
            item = form.save(commit=False) 
            item.created_by = request.user
            item.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = NewItemForm()
    return render(request,'item/form.html',{
        'form':form,
        'title': 'Add New Item'
    })

@login_required
def edit(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by=request.user)
    if request.method == "POST":
        form=EditItemForm(request.POST,request.FILES,instance=item)
        if form.is_valid:
            form.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = EditItemForm(instance=item)
    return render(request,'item/form.html',{
        'form':form,
        'title': 'Edit Item'
    })

@login_required
def delete(request,pk):
    item = get_object_or_404(Item,pk=pk,created_by=request.user)
    item.delete()
    return redirect('myitems:index')

myitems/views.py
from django.shortcuts import render
from item.models import Item
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    items=Item.objects.filter(created_by=request.user)
    return render(request,'myitems/index.html',{
        'items': items
    })

core/templates/core/base.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Order Manager</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="bg-[#1f2937]">
    <nav
      class=" fixed top-0 w-full"
    >
    <div class="py-6 px-6 flex justify-between items-center bg-[#1f2937] opacity-100 drop-shadow-lg mb-20">
      <div class="w-1/2 flex flex-rows justify-between p-2">
      <a href="/" class="text-xl text-white font-semibold flex-start">Order Manager</a>
      <div class="w-1/2 mr-12">
      <form method="get" action="{% url 'core:item_search' %}" class="flex items-center w-full ">
        <input
            type="text"
            name="q"
            placeholder="Search for items"
            class="px-2 py-1 border border-gray-300 rounded-md w-full rounded-xl "
        />
    </form>
  </div>
  </div>
      <div class="space-x-6">
      <div class="flex flex-rows">
        <a
          href="/"
          class="px-6 py-3 text-lg font-semibold text-white rounded-xl hover:bg-gray-900"
          >Home</a
        >
        {% if request.user.is_authenticated %}
        <a
          href="{%url 'myitems:index'%}"
          class="px-6 py-3 text-lg font-semibold text-white rounded-xl hover:bg-gray-900"
          >My Items</a
        >
        <a
          href="{%url 'item:new'%}"
          class="px-6 py-3 text-lg font-semibold text-white rounded-xl hover:bg-gray-900"
          >Add Item</a
        >
        <form action="{%url 'core:logout'%}" method="post">
        {% csrf_token %}
        <button type='submit' class="px-6 py-3 text-lg font-semibold text-white rounded-xl hover:bg-gray-900"> Log out </button>
          </form>
        {% else %}
        <a
        href="{% url 'core:signup' %}"
        class="px-6 py-3 text-lg font-semibold text-white rounded-xl hover:bg-gray-900"
        >Sign up</a
      >
    
      <a
        href="{% url 'core:login' %}"
        class="px-6 py-3 text-lg font-semibold text-white rounded-xl hover:bg-gray-900"
        >Log in</a
      >
            
        {% endif %}
      </div>
    </div>
  </div>
    </nav>
    <div class="p-6 mt-12">{% block content %} {% endblock %}</div>
    <footer class="py-6 px-6 flex justify-between  bg-[#111827] drop-shadow-lg">
      <div class="w-2/3 pr-10">
          <h3 class="mb-5 font-semibold text-gray-400">About</h3>

          <p class="text-lg text-gray-500">
            Our eCommerce website is more than just an online store; it's a reflection of our passion for delivering quality products and exceptional service to our valued customers. At Order Manager, we're dedicated to creating a seamless shopping experience that goes beyond transactions. Founded on the principles of trust, innovation, and customer-centricity, our journey began with a vision to provide a diverse range of products that cater to your needs and desires.
          </p>
      </div>

      {% comment %} <div class="w-1/3">
          <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

          <ul class="space-y-2">
              <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
              <li><a href="{% url 'contact'%}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
              <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
              <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
          </ul>
      </div> {% endcomment %}
  </footer>
  </body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{%block content%}
    <h1 class="mt-20 h-screen"> contact </h1>
{%endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="mt-6 px-10 py-12 bg-[#111827] rounded-xl">
        <h2 class="mb-12 text-white text-2xl text-center">All Items</h2>

        <div class="grid grid-cols-3 gap-5 ">
            {% for item in items %}
            <div class="flex flex-col items-center">  
                <a href="{% url 'item:detail' item.id %}">
                    <div class="w-fit">
                        <img src="{{ item.image.url }}" class="h-60 w-72 rounded-t-xl">
                    </div>

                    <div class="p-6 bg-slate-600 rounded-b-xl w-72">
                        <h2 class="text-2xl text-white">{{ item.name }}</h2>
                        <p class="text-gray-200">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
    </div>

    {% comment %} <div class="mt-6 px-6 py-12 rounded-xl bg-[#111827] ">
        <h2 class="mb-12 text-2xl text-center text-white">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-2 bg-gray-600 rounded-b-xl">
                            <h2 class="text-xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div> {% endcomment %}
{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}


{% block content %}

<div class="my-20 w-1/2 bg-slate-700 text-white mx-auto rounded-xl p-5">
    <h1 class="mb-6 text-3xl">Login</h1>
    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="text-slate-200 inline-block"> Username </label> <br> {{form.username}}
        </div>
       
        <div class="mb-3">
            <label class="text-slate-200 inline-block"> Password </label> <br> {{form.password}}
        </div>
        {%if form.non_field_errors or form.errors%}
        <div class="mb-3 bg-red-400 p-3 rounded-xl">
            {% for field in form  %}
                {{field.errors}}
            {% endfor %}
            {{form.non_field_errors}}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg mt-5 bg-cyan-700 hover:bg-cyan-900 text-white rounded-xl"> Submit</button>
    </form>
</div>

{% endblock %}

core/templates/core/search_result.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="mt-6 px-10 py-12 bg-[#111827] rounded-xl">
        <h2 class="mb-12 text-2xl text-white text-center"> Your Results</h2>

        <div class="grid grid-cols-3 gap-5 ">
            {% for item in items %}
            <div class="flex flex-col items-center">  
                <a href="{% url 'item:detail' item.id %}">
                    <div class="w-fit">
                        <img src="{{ item.image.url }}" class="h-60 w-72 rounded-t-xl">
                    </div>

                    <div class="p-6 bg-slate-600 rounded-b-xl w-72">
                        <h2 class="text-2xl text-white ">{{ item.name }}</h2>
                        <p class="text-gray-200">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% empty %}
            <div class="w-full h-screen">
                <h2 class="text-xl  text-white">Oops, No items found :( </h2>
            </div>
        {% endfor %}
        </div>
    </div>

{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}


{% block content %}

<div class="my-20 w-1/2 bg-slate-700 text-white mx-auto rounded-xl p-5">
    <h1 class="mb-6 text-3xl">Sign Up </h1>
    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="text-slate-200 inline-block"> Username </label> <br> {{form.username}}
        </div>
        <div class="mb-3">
            <label class="text-slate-200 inline-block"> Email </label> <br> {{form.email}}
        </div>
        <div class="mb-3">
            <label class="text-slate-200 inline-block"> Password </label> <br> {{form.password1}}
        </div>
        <div class="mb-3">
            <label class="text-slate-200 inline-block"> Repeat Password </label> <br> {{form.password2}}
        </div>
        {%if form.non_field_errors or form.errors%}
        <div class="mb-3 bg-red-400 p-3 rounded-xl">
            {% for field in form  %}
                {{field.errors}}
            {% endfor %}
            {{form.non_field_errors}}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg mt-5 bg-cyan-700 hover:bg-cyan-900 text-white rounded-xl"> Submit</button>
    </form>
</div>

{% endblock %}

item/templates/item/detail.html
{% extends "core/base.html" %}
{% block title %}{{item.name}}{% endblock %}
{% block content %}

<div class="grid grid-cols-5 gap-2  items-center px-28 mt-20 ">
    <div class="col-span-3 p-3">
        <img src={{item.image.url}} class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-700 rounded-xl">
        <h1 class="mb-6 text-3xl text-white">{{ item.name }}</h1>
        <p class="text-gray-200"><strong>Price: </strong>{{ item.price }}</p>
        <p class="text-gray-200"><strong>Seller: </strong>{{ item.created_by.username }}</p>
        {% if item.description %}
            <p class="text-gray-300">
                <strong class="text-gray-200">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
        {% if item.priority_tag %}
        <p class="text-gray-200 "> <strong> Priority: </strong> {{ item.priority_tag.name }}</p>
    {% endif %}
    {% if request.user == item.created_by %}
            <div class=" mt-1 p-6 bg-slate-600 rounded-xl">
                <p class="text-slate-100 mb-3  p-2 text-xl"> This is your item! </p>
                <a href="{%url 'item:delete' item.id %}" class="bg-red-600 w-24 hover:bg-red-800 m-4 text-white font-bold p-3 px-8 rounded-xl">
                    Delete 
                </a>
                <a href="{%url 'item:edit' item.id %}" class="bg-teal-600 hover:bg-teal-800 m-4 text-white font-bold p-3 px-8 rounded-xl">
                    Edit 
                </a>
            </div>
    {% endif %}
    </div>
</div>
{% if related_items %}
<div class="mt-6 px-6 py-12 bg-[#111827] rounded-xl ">
    <h2 class="mb-12 text-2xl text-center text-white ">Related items</h2>
<div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
        <div>
            <a href = "{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class="rounded-t-xl h-60 w-72">
                </div>

                <div class="p-6 bg-slate-600 rounded-b-xl w-72">
                    <h2 class="text-2xl text-white">{{ item.name }}</h2>
                    <p class="text-gray-200">Price: {{ item.price }}</p>                
                </div>
            </a>
        </div>
    {% endfor %}
</div>
</div>
{% endif %}
{% endblock %}

item/templates/item/form.html
{% extends "core/base.html" %}

{% block content %}

    <h1 class="my-6 text-3xl text-white font-bold text-center mt-12">{{title}} </h1>
    <div class="flex justify-center bg-slate-700 text-white rounded-xl mx-14 p-4">
    <form method='post' action="." enctype="multipart/form-data" class="w-1/2  ">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
        {%if form.non_field_errors or form.errors%}
        <div class="mb-3 bg-red-400 p-3 rounded-xl">
            {% for field in form  %}
                {{field.errors}}
            {% endfor %}
            {{form.non_field_errors}}
        </div>
        {% endif %}
        <div class="flex w-full justify-center">
        <button class="py-2 mt-6 px-6 text-lg mt-5 bg-cyan-700 hover:bg-cyan-900 text-white rounded-xl"> Submit</button>
        </div>
    </form>
</div>
{% endblock %}

myitems/templates/myitems/index.html
{% extends 'core/base.html' %}
 
{% block content %}
    <div class="mt-6 px-10 py-12 bg-[#111827] rounded-xl">
        <h2 class="mb-12 text-white text-2xl text-center">My Items</h2>

        <div class="grid grid-cols-3 gap-5 ">
            {% for item in items %}
            <div class="flex flex-col items-center">  
                <a href="{% url 'item:detail' item.id %}">
                    <div class="w-fit">
                        <img src="{{ item.image.url }}" class="h-60 w-72 rounded-t-xl">
                    </div>

                    <div class="p-6 bg-slate-600 rounded-b-xl w-72">
                        <h2 class="text-2xl text-white">{{ item.name }}</h2>
                        <p class="text-gray-200">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% empty %}
            <div class="w-full h-screen">
                <h2 class="text-xl  text-white">Oops, No items found :( </h2>
            </div>
        {% endfor %}
        </div>
    </div>

   
{% endblock %}